job('First-Maven-Project-Via-DSL') {
  description("First Maven job generated by the DSL on ${new Date()}, the project is small Maven project hosted on github")
  scm {https://github.com/jdevopser/jenkins-maven-project", 'main')
  }
  triggers {
      scm('* * * * *')
  }
  steps {
      maven('clean package', 'single-module/pom.xml')
  }
  publishers {
      //archive the war file generated
      archiveArtifacts '**/*.jar'
  }
}
    
